
#define ALPHA_PATCH 0
#define CASEINSENSITIVE_PATCH 1
#define FUZZYMATCH_PATCH 1
#define LINE_HEIGHT_PATCH 1
#define NUMBERS_PATCH 1
#define MOUSE_SUPPORT_PATCH 1
#define PREFIXCOMPLETION_PATCH 0
#define FUZZYHIGHLIGHT_PATCH 0
#define HIGHLIGHT_PATCH 0
#define CENTER_PATCH 0

